[build-system]
requires = ["setuptools >= 61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "aiidalab-mlip"
version = "0.1.0a1"
authors = [
    {name = "Jessica Gould"},
    {name = "Jacob Wilkins", email = "jacob.wilkins@stfc.ac.uk"}
]
description = "Run MLIPs through AiiDALab."
readme = "README.md"
requires-python = ">=3.10,<=3.12"
classifiers = [
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Development Status :: 1 - Planning"
]
license = {text = "BSD-3-Clause"}
dependencies = [
    "aiidalab>=21.09.0",
    "aiida-mlip",
    "aiidalab-widgets-base",
    "traitlets~=5.0",
    "pydantic>=2.6,<3",
    "ipywidgets==7.7.4",
    "ipython==8.10.0",
    "psycopg==3.2.3",
    "cryptography<46",
    "importlib-metadata==6.11.0",
    "jedi==0.18.2",
    "psutil==5.9.8",
    "nglview",
    "alc-aiidalab-widgets",
    "pyyaml",
]

[project.optional-dependencies]
rdkit = ["rdkit"]
tests = [
    "pytest>=7.0",
]

[project.urls]
Homepage = "https://github.com/stfc/aiidalab-mlip"
Logo = "https://raw.githubusercontent.com/stfc/aiidalab-mlip/main/img/logo.png"
Documentation = "https://github.com/stfc/aiidalab-mlip#readme"
"Bug Tracker" = "https://github.com/stfc/aiidalab-mlip/issues"

[tool.ruff]
line-length = 100
indent-width = 4

[tool.ruff.lint]
# Allow unused variables when underscore-prefixed.
preview = true
select = [
    "PL",  # Pylint
    "E",   # Pycodestyle
    "W",   # Pycodestyle warnings
    "F",   # Pyflakes
    "B",   # Flake8 bugbear
    "SIM", # Flake8 Simplify
    "A",   # Flake8 builtins
    "COM", # Flake8 commas
    "ISC", # Flake8 implicit string concat
    "RSE", # Flake8 raise
    "FA",  # Flake8 future
    "FBT", # Flake8 boolean trap
    "C4",  # Flake8 comprehensions
    "Q",   # Flake8 Quotes
    "RET", # Flake8 return
    "ARG", # Flake8 unused args
    "PTH", # Flake8 use pathlib
    "YTT", # Flake8 2020
    "ANN", # Flake8 annotations
    "BLE", # Flake8 Blind except
    "C4",  # Flake8 comprehensions
    "T10", # Flake8 debugger statements
    "T20", # Flake8 Print
    "FIX", # Flake8 Fixme
    "LOG", # Flake8 Logging
    "G",   # Flake8 Logging format
    "PIE", # Flake8 Pie
    "I",   # Isort
    "PERF",# Perflint
    "RUF", # Ruff specific
    "FURB",# Refurb
    "PERF",# Perflint
    "D",   # Pydocstyle
    "DOC", # Pydoclint
    "UP",  # Pyupgrade
]
ignore = [
    "PLR0912",  # Too many branches
    "PLR0913",  # Too many arguments
    "PLR0914",  # Too many locals
    "PLR0915",  # Too many statements
    "PLW2901",  # For loop variable overwritten
    "ANN401",   # No typing.Any
    "RUF067",   # Require empty init
    "LOG015",   # Call to base logger
    "COM812",   # Commas
]
allowed-confusables = ["α", "β", "γ", "꞉"]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.isort]
profile = "black"

[tool.numpydoc_validation]
checks = [
    "all",   # report on all checks, except the below
    "EX01",
    "SA01",
    "ES01",
]
# remember to use single quotes for regex in TOML
exclude = [  # don't report on objects that match any of these regex
    '\.undocumented_method$',
    '\.__[^.]*__$',
]
override_SS05 = [  # override SS05 to allow docstrings starting with these words
    '^Process ',
    '^Assess ',
    '^Access ',
    '^Class ',
]

[tool.pytest.ini_options]
minversion = "7.0"
testpaths = ["tests"]
pythonpath = ["src", "."]
addopts = "-v -p no:pytest-qt"
