[aiidalab]
title = MLIP
categories =
    quantum
    classical

[metadata]
name = aiidalab-mlip
version = 0.1.0a1
author = Jacob Wilkins and Jessie Gould
author_email = jacob.wilkins@stfc.ac.uk
description = Wrapper for Janus
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/stfc/aiidalab-mlip
project_urls =
    Logo = https://raw.githubusercontent.com/stfc/aiida-mlip/main/docs/source/images/aiida-mlip-100.png
    Source = https://github.com/stfc/aiidalab-mlip
    Bug Tracker = https://github.com/stfc/aiidalab-mlip/issues
    Documentation = https://stfc.github.io/aiidalab-mlip
classifiers =
    Framework :: AiiDA
    Operating System :: OS Independent
    Programming Language :: Python :: 3
    Development Status :: 4 - Beta
license_file = LICENSE


[options]
package_dir =
    = src
packages = find:
install_requires =
    aiidalab>=21.09.0
    aiida-mlip
    aiidalab-widgets-base
    traitlets~=5.0
    pydantic>=2.6,<3
    ipywidgets==7.7.4
    ipython==8.10.0
    psycopg==3.2.3
    cryptography<46
    importlib-metadata==6.11.0
    jedi==0.18.2
    psutil==5.9.8
    nglview
    alc-aiidalab-widgets

python_requires = >=3.10,<3.13

[options.packages.find]
where = src

[options.extras_require]
rdkit =
      rdkit
